---
- id: CPANSA-Config-Model-2017-03
  distribution: Config-Model
  reported: 2017-05-10
  description: >
    The gen_class_pod implementation in lib/Config/Model/Utils/GenClassPod.pm in Config-Model (aka libconfig-model-perl)
    before 2.102 has a dangerous "use lib" line, which allows remote attackers to have an unspecified impact via
    a crafted Debian package file.
  references:
    - https://metacpan.org/changes/distribution/Config-Model
    - https://github.com/dod38fr/config-model/commit/9bd64d9ec6c0939166a2216a37d58dd19a725951
  cves:
    - CVE-2017-0373
  affected_versions: "<2.102"
  fixed_versions: ">=2.102"
- id: CPANSA-Config-Model-2017-02
  distribution: Config-Model
  reported: 2017-05-10
  description: >
    Loads models from a local directory, making it possible to substitute the model.
  references:
    - https://metacpan.org/changes/distribution/Config-Model
    - https://github.com/dod38fr/config-model/commit/4d37c75b0c4f9633b67999f8260b08027a6bc524
  affected_versions: "<2.102"
  fixed_versions: ">=2.102"
- id: CPANSA-Config-Model-2017-01
  distribution: Config-Model
  reported: 2017-05-10
  description: >
    YAML or YAML::XS can be loaded automatically making it possible to run arbitrary code loading a specially crafted YAML file.
  references:
    - https://metacpan.org/changes/distribution/Config-Model
    - https://github.com/dod38fr/config-model/commit/01d212348bfbadf31bd74aadd26b1e391ff2fd92
  affected_versions: "<2.102"
  fixed_versions: ">=2.102"
