
---
- id: CPANSA-CGI-Application-Dispatch-2005-001
  distribution: CGI-Application-Dispatch
  reported: 2005-01-20
  description: >
    Untainted module names.
  references:
    - https://metacpan.org/changes/distribution/CGI-Application-Dispatch
  affected_versions: "<1.02"
  fixed_versions: ">=1.02"
