---
name: validate YAML files

on:
    push:
        branches:
            - '**'
            - '!**release**'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths:
            - 'cpansa/**.yml'
            - '.github/workflows/validate.yml'
        pull_request:

jobs:
    yaml:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: 'Yamllint'
              uses: karancode/yamllint-github-action@master
              with:
                  yamllint_file_or_dir: 'cpansa'
                  yamllint_strict: false
                  yamllint_comment: true
