name: validate YAML files

on:
    push:
        branches:
            - '**'
            - '!**release**'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths:
            - 'cpansa/**.yml'
            - '.github/workflows/validate.yml'
        pull_request:

jobs:
    yaml:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install yamllint
              run: sudo apt-get install yamllint
            - name: Run tests
              run: |
                yamllint --format github cpansa/*.yml
